theme = "bogster"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [120]
true-color = true
scroll-lines = 12
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
left = "goto_previous_buffer"
right = "goto_next_buffer"
up = "no_op"
down = "no_op"
C-up = ":buffer-close"
C-down = ":buffer-close-others"
C-s = ":write-quit"
C-d = ":o /home/mawjad/Documents/GitHub/"
C-o = ":open ~/.config/helix/languages.toml"
C-q =":buffer-close!"
ret = "insert_mode"
j = "move_char_left" 
k = "move_line_up"
l = "move_line_down"
';' = "move_char_right"
'C-r' = ":config-reload"


[keys.insert]
C-s = ":w"
C-o = ":open ~/.config/helix/config.toml"
C-x = ":run-shell-command go run main.go"
