[language-server.gdscript-lsp]
command = "nc"
args = ["127.0.0.1", "6008"]

[[language]]
name = "gdscript"
scope = "source.gdscript"
injection-regex = "gd"
file-types = ["gd"]
roots = ["project.godot", ".git"]
language-servers = ["gdscript-lsp"]
language-id = "gdscript"

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.mod", ".git"]
language-servers = ["gopls"]
language-id = "go"

[[language]]
name = "zig"
scope = "source.zig"
injection-regex = "zig"
file-types = ["zig"]
roots = [""]
language-servers = ["zls"]
language-id = "zig"

[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
roots = [".nix"]
language-servers = ["nil"]
language-id = "nix"

[[language]]
name = "bash"
language-servers =[ "bash-language-server"]
