[[language-bash]]
language-servers = ["bash-language-server"]
name = "bash"

[[language-go]]
file-types = ["go"]
injection-regex = "go"
language-id = "go"
language-servers = ["gopls"]
name = "go"
roots = ["go.mod", ".git"]
scope = "source.go"

[[language-nix]]
file-types = ["nix"]
injection-regex = "nix"
language-id = "nix"
language-servers = ["nil"]
name = "nix"
roots = [".nix"]
scope = "source.nix"

[[language]]
name = "rust"
auto-format = false

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language-zig]]
file-types = ["zig"]
injection-regex = "zig"
language-id = "zig"
language-servers = ["zls"]
name = "zig"
roots = [""]
scope = "source.zig"

